name: iot_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  syncfusion_flutter_charts: ^20.4.54
  syncfusion_flutter_gauges: ^20.4.54
  syncfusion_flutter_core: ^20.4.54
  cupertino_icons: ^1.0.8
  mqtt_client: ^9.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
